name: ng-gh-test-workflow
on:
  push:
    branches: 
      - master
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.12.0
        cache: 'npm'
    - run: npm install
    - run: ./node_modules/@angular/cli/bin/ng.js build
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - run: sudo apt install -y chromium-browser
      - run: export CHROME_BIN="/usr/bin/chromium-browser"
      - run: npm install
      - run: ./node_modules/@angular/cli/bin/ng.js test --no-progress --no-watch --browsers=ChromeHeadless --code-coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - run: npm install
      - run: ./node_modules/@angular/cli/bin/ng.js lint

